// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teijwcdwygszubvuwilg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaWp3Y2R3eWdzenVidnV3aWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTc3NzIsImV4cCI6MjA3Mzg3Mzc3Mn0.86YKngQyTxtvISItxBihr9TINArC5cgkWibx5zOEx0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});